INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (0, 'United States', 9694176, 238656, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (1, 'India', 8313876, 123650, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (2, 'Brazil', 5567126, 160548, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (3, 'Russia', 1693454, 29217, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (4, 'France', 1502763, 38289, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (5, 'Spain', 1331756, 36495, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (6, 'Argentina', 1195276, 32052, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (7, 'Colombia', 1099392, 31847, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (8, 'United Kingdom', 1073882, 47250, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (9, 'Mexico', 938405, 92593, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (10, 'Peru', 908902, 34623, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (11, 'Italy', 759829, 39412, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (12, 'South Africa', 728836, 19539, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (13, 'Iran', 646164, 36579, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (14, 'Germany', 577131, 10883, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (15, 'Chile', 514202, 14319, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (16, 'Iraq', 482296, 11068, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (17, 'Belgium', 452541, 12126, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (18, 'Poland', 439536, 6475, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (19, 'Indonesia', 421731, 14259, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (20, 'Ukraine', 420617, 7731, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (21, 'Bangladesh', 414164, 6004, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (22, 'Philippines', 388137, 7367, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (23, 'Turkey', 382118, 10481, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (24, 'Netherlands', 375890, 7576, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (25, 'Czech Republic (Czechia)', 362985, 3913, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (26, 'Saudi Arabia', 348510, 5456, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (27, 'Pakistan', 337573, 6867, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (28, 'Israel', 316792, 2592, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (29, 'Romania', 258437, 7273, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (30, 'Canada', 244935, 10279, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (31, 'Morocco', 229565, 3900, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (32, 'Switzerland', 182303, 2471, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (33, 'Nepal', 179614, 1004, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (34, 'Ecuador', 170110, 12698, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (35, 'Portugal', 149443, 2635, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (36, 'Bolivia', 141936, 8751, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (37, 'United Arab Emirates', 136149, 503, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (38, 'Panama', 135592, 2731, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (39, 'Sweden', 134532, 5969, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (40, 'Qatar', 133143, 232, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (41, 'Kuwait', 128080, 789, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (42, 'Dominican Republic', 127848, 2252, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (43, 'Austria', 118198, 1192, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (44, 'Oman', 116528, 1264, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (45, 'Kazakhstan', 113741, 1857, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (46, 'Costa Rica', 112120, 1419, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (47, 'Guatemala', 108483, 3748, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (48, 'Egypt', 108122, 6305, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (49, 'Japan (+Diamond Princess)', 102993, 1793, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (50, 'Belarus', 102313, 995, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (51, 'Honduras', 98688, 2706, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (52, 'Ethiopia', 97502, 1494, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (53, 'Armenia', 97150, 1448, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (54, 'Venezuela', 93100, 810, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (55, 'Hungary', 90988, 2063, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (56, 'Jordan', 86576, 967, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (57, 'China', 86087, 4634, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (58, 'Lebanon', 85209, 667, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (59, 'Bahrain', 82363, 324, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (60, 'Moldova', 77487, 1838, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (61, 'Uzbekistan', 67698, 575, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (62, 'Slovakia', 66772, 261, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (63, 'Paraguay', 64628, 1441, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (64, 'Libya', 64587, 900, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (65, 'Tunisia', 64363, 1512, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (66, 'Nigeria', 63173, 1151, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (67, 'Ireland', 63048, 1922, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (68, 'Kyrgyzstan', 60774, 1163, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (69, 'Bulgaria', 60537, 1412, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (70, 'Algeria', 58979, 1980, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (71, 'Azerbaijan', 58282, 768, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (72, 'Singapore', 58036, 28, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (73, 'Kenya', 57093, 1039, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (74, 'Croatia', 56567, 654, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (75, 'Myanmar', 55804, 1307, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (76, 'State of Palestine', 55408, 501, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (77, 'Bosnia and Herzegovina', 53822, 1317, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (78, 'Serbia', 51083, 844, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (79, 'Denmark', 49594, 728, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (80, 'Ghana', 48200, 320, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (81, 'Georgia', 46817, 381, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (82, 'Greece', 44246, 655, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (83, 'Afghanistan', 41814, 1548, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (84, 'Slovenia', 37382, 412, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (85, 'Malaysia', 35425, 271, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (86, 'El Salvador', 34015, 992, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (87, 'North Macedonia', 33908, 1049, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (88, 'Australia', 27620, 907, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (89, 'South Korea', 26925, 474, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (90, 'Cameroon', 22103, 429, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (91, 'Norway', 21956, 282, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (92, 'Albania', 21904, 532, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (93, 'Côte d''Ivoire', 20765, 126, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (94, 'Montenegro', 19977, 322, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (95, 'Luxembourg', 19634, 167, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (96, 'Lithuania', 18092, 182, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (97, 'Madagascar', 17111, 244, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (98, 'Finland', 16902, 359, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (99, 'Zambia', 16698, 349, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (100, 'Senegal', 15650, 326, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (101, 'Sudan', 13905, 837, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (102, 'Mozambique', 13202, 95, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (103, 'Uganda', 13099, 115, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (104, 'Namibia', 13030, 133, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (105, 'Guinea', 12260, 73, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (106, 'Maldives', 11796, 38, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (107, 'Sri Lanka', 11744, 23, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (108, 'Angola', 11577, 291, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (109, 'DR Congo', 11427, 315, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (110, 'Tajikistan', 11139, 83, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (111, 'French Guiana', 10577, 70, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (112, 'Jamaica', 9296, 214, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (113, 'Haiti', 9057, 232, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (114, 'Gabon', 8984, 55, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (115, 'French Polynesia', 8949, 38, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (116, 'Cabo Verde', 8944, 95, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (117, 'Zimbabwe', 8410, 246, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (118, 'Guadeloupe', 7903, 133, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (119, 'Mauritania', 7724, 164, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (120, 'Cuba', 7035, 129, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (121, 'Bahamas', 6790, 149, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (122, 'Latvia', 6752, 85, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (123, 'Botswana', 6642, 24, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (124, 'Malta', 6506, 64, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (125, 'Eswatini', 5942, 117, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (126, 'Malawi', 5934, 184, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (127, 'Réunion', 5898, 26, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (128, 'Syria', 5888, 298, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (129, 'Trinidad and Tobago', 5754, 110, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (130, 'Djibouti', 5575, 61, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (131, 'Nicaragua', 5514, 156, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (132, 'Hong Kong', 5349, 105, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (133, 'Congo', 5348, 92, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (134, 'Estonia', 5333, 73, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (135, 'Suriname', 5218, 111, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (136, 'Rwanda', 5162, 35, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (137, 'Equatorial Guinea', 5089, 83, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (138, 'Iceland', 4958, 17, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (139, 'Cyprus', 4934, 27, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (140, 'Andorra', 4910, 75, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (141, 'Central African Republic', 4866, 62, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (142, 'Aruba', 4538, 38, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (143, 'Mayotte', 4524, 45, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (144, 'Guyana', 4245, 128, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (145, 'Somalia', 4229, 107, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (146, 'Thailand', 3804, 59, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (147, 'Belize', 3790, 61, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (148, 'Gambia', 3679, 120, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (149, 'Mali', 3584, 136, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (150, 'Martinique', 3552, 30, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (151, 'Uruguay', 3196, 61, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (152, 'South Sudan', 2940, 59, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (153, 'Benin', 2683, 41, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (154, 'Burkina Faso', 2530, 67, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (155, 'Guinea-Bissau', 2413, 41, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (156, 'Togo', 2381, 57, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (157, 'Sierra Leone', 2368, 74, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (158, 'Yemen', 2063, 601, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (159, 'New Zealand', 1971, 25, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (160, 'Lesotho', 1961, 44, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (161, 'Chad', 1513, 98, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (162, 'Liberia', 1436, 82, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (163, 'Niger', 1222, 69, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (164, 'Vietnam', 1203, 35, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (165, 'Curaçao', 1000, 1, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (166, 'San Marino', 994, 42, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (167, 'Sao Tome & Principe', 954, 16, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (168, 'Channel Islands', 879, 48, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (169, 'Sint Maarten', 859, 22, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (170, 'Gibraltar', 730, 0, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (171, 'Turks and Caicos', 704, 6, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (172, 'Liechtenstein', 631, 3, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (173, 'Papua New Guinea', 597, 7, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (174, 'Burundi', 597, 1, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (175, 'Taiwan', 568, 7, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (176, 'Saint Martin', 566, 9, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (177, 'Comoros', 545, 7, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (178, 'Tanzania', 509, 21, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (179, 'Faeroe Islands', 495, 0, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (180, 'Eritrea', 480, 0, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (181, 'Mauritius', 451, 10, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (182, 'Monaco', 397, 2, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (183, 'Bhutan', 358, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (184, 'Isle of Man', 356, 24, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (185, 'Mongolia', 352, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (186, 'Cambodia', 292, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (187, 'Cayman Islands', 242, 1, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (188, 'Barbados', 238, 7, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (189, 'Bermuda', 206, 9, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (190, 'Seychelles', 157, 0, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (191, 'Caribbean Netherlands', 153, 3, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (192, 'Brunei ', 148, 3, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (193, 'Antigua and Barbuda', 128, 3, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (194, 'Saint Lucia', 97, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (195, 'Saint Barthelemy', 83, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (196, 'St. Vincent & Grenadines', 75, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (197, 'British Virgin Islands', 71, 1, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (198, 'Dominica', 50, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (199, 'Macao', 46, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (200, 'Fiji', 34, 2, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (201, 'Timor-Leste', 30, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (202, 'Grenada', 29, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (203, 'New Caledonia', 28, 0, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (204, 'Holy See', 27, 0, 'Europe');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (205, 'Laos', 24, 0, 'Asia');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (206, 'Saint Kitts & Nevis', 19, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (207, 'Greenland', 17, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (208, 'Saint Pierre & Miquelon', 16, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (209, 'Montserrat', 13, 1, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (210, 'Falkland Islands', 13, 0, 'South America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (211, 'Solomon Islands', 13, 0, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (212, 'Western Sahara', 10, 1, 'Africa');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (214, 'Anguilla', 3, 0, 'North America');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (215, 'Marshall Islands', 2, 0, 'Australia/Oceania');
INSERT INTO public.country (id, name, numberofcases, deaths, continentname) VALUES (216, 'Wallis & Futuna', 1, 0, 'Australia/Oceania');